apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-deployment
  namespace: argocd
  labels:
    app: mobile
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mobile
  template:
    metadata:
      labels:
        app: mobile
    spec:
      containers:
      - name: mobile
        image: 864981759039.dkr.ecr.ap-southeast-1.amazonaws.com/back_repo:15
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mobile-srv
  namespace: argocd 
spec:
  type: ClusterIP
  selector:
    app: mobile           
  ports:
    - protocol: TCP
      port: 8080                      
      targetPort: 80
---      
