apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-deployment
  namespace: dev
  labels:
    app: mobile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobile
  template:
    metadata:
      labels:
        app: mobile
    spec:
      containers:
      - name: mobile
        image: 339712867708.dkr.ecr.ap-southeast-1.amazonaws.com/proj_repo:latest
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mobile-srv
  namespace: dev   
spec:
  type: ClusterIP
  selector:
    app: mobile           
  ports:
    - protocol: TCP
      port: 80                      
      targetPort: 80
---      
